# Generated by Django 3.2.12 on 2022-07-11 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '계정 관리', 'verbose_name_plural': '계정 관리'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='유저 id'),
        ),
        migrations.CreateModel(
            name='SocialLoginLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('K', '카카오'), ('A', '애플')], max_length=5, verbose_name='소셜 타입')),
                ('social_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='소셜 아이디')),
                ('social_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='소셜 이메일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
