version: "3.7"

services:
    web:
        build:
            context: ./django
            dockerfile: Dockerfile
        image: test/django
        container_name: test-django
        env_file:
            - ./.env.prod
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./django:/usr/src/app/
        ports:
            - 8000:8000
